// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mission6_Keeney.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Mission6_Keeney.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Frank Darabont",
                            Edited = false,
                            Genre = "Drama",
                            LentTo = "Ben",
                            Notes = "The best movie ever!",
                            Rating = "R",
                            ReleaseYear = 1994,
                            Title = "Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Anthony J. Russo",
                            Edited = false,
                            Genre = "Action",
                            LentTo = "Ben",
                            Notes = "Awesome movie!",
                            Rating = "PG-13",
                            ReleaseYear = 2019,
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Christopher Nolan",
                            Edited = false,
                            Genre = "Action",
                            LentTo = "Ben",
                            Notes = "Long but good!",
                            Rating = "PG-13",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
